shape: 31,174
isotherms:
  - 100
  - 200
  - 800
levels: 20
colormap: hot
sample_tag: MuscAr
figure_size: 20,6 #supercedes vertical_exaggeration
vector_map:
  "0000": v_11
use_unique_output_root: False
vertical_exaggeration: 1.25
vector_downsample: 1
vector_color: blue
vector_every_n: 10
colormap_min: 0
colormap_max: 1000
combine_temperature_position: True
combine_temperature_vectors: True
label_isotherms: True
